version: '3.9'

services:
  workspace:
    container_name: java-workspace
    build:
      context: ./docker/workspace
      args:
        USER_NAME: ${USER_NAME:-vscode}
        USER_GROUP_NAME: ${USER_GROUP_NAME:-workspace}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    tty: true
    volumes:
      - ../:/home/${USER_NAME}/workspace:cache
    ports:
      - 5555:5555
